from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import *

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('login/', UserLoginView.as_view(next_page='home'), name='login'),
    path('logout/', LogoutView.as_view(next_page='home'), name='logout'),
    path('bolle/', BollaListView.as_view(), name='bolle-list'),
    path('bolle/<int:pk>/', BollaDetailView.as_view(), name='bolla-detail'),
    path('bolle/create/', BollaCreateView.as_view(), name='bolla-create'),
    path('bolle/<int:pk>/update/', BollaUpdateView.as_view(), name='bolla-update'),
    path('bolle/<int:pk>/delete/', BollaDeleteView.as_view(), name='bolla-delete'),
    path('bolle/<int:pk>/rigadelete/', RigaBollaDeleteView.as_view(), name='riga-delete'),
    path('bolle/<int:pk>/stampa/', BollaStampaView.as_view(), name='bolla-stampa'),
    path('edit/articoli-concessi/<int:pk>/', ArticoliConcessiUpdateView.as_view(), name='articoli-concessi-update'),
    path('bolle/import-file/', ImportFileView.as_view(), name='import-file'),
    path('confirm-import/', ConfirmImportView.as_view(), name='confirm-import'),
    path('bolle/export-file/', ExportBolleView.as_view(), name='export-file'),
    path('carichi/', CaricoListView.as_view(), name='carichi-list'),
    path('carichi/<int:pk>/', CaricoDetailView.as_view(), name='carico-detail'),
    path('carichi/create/', CaricoCreateView.as_view(), name='carico-create'),
    path('carichi/<int:pk>/update/', CaricoUpdateView.as_view(), name='carico-update'),
    path('carichi/<int:pk>/delete/', CaricoDeleteView.as_view(), name='carico-delete'),
    path('carichi/<int:pk>/rigadelete/', RigaCaricoDeleteView.as_view(), name='riga-carico-delete'),
    path('resi/', ResoListView.as_view(), name='resi-list'),
    path('resi/<int:pk>/', ResoDetailView.as_view(), name='reso-detail'),
    path('resi/create/', ResoCreateView.as_view(), name='reso-create'),
    path('resi/<int:pk>/update/', ResoUpdateView.as_view(), name='reso-update'),
    path('resi/<int:pk>/delete/', ResoDeleteView.as_view(), name='reso-delete'),
    path('resi/<int:pk>/rigadelete/', RigaResoDeleteView.as_view(), name='riga-reso-delete'),
    path('riepiloghi/', menu_riepiloghi, name="menu-riepiloghi"),
    path('riepiloghi/giornaliero/', riepilogo_giornaliero, name='riepilogo-giornaliero'),
    path('riepiloghi/casse/', riepilogo_casse, name='riepilogo-casse'),
    path('riepiloghi/giornaliero/stampa/', riepilogo_giornaliero_stampa, name='riepilogo-stampa'),
    path('riepiloghi/cliente/', riepilogo_cliente, name='riepilogo-cliente'),
    path('riepiloghi/cls/', riepilogo_cls, name='riepilogo-cls'),
    path('bulk_update/', bulk_update_view, name='bulk-update'),
    path('fatture/', FatturaListView.as_view(), name='fatture-list'),
    path('fatture/<int:pk>/', FatturaDetailView.as_view(), name='fattura-detail'),
    path('fatture/create/', FatturaCreateView.as_view(), name='fattura-create'),
    path('fatture/<int:pk>/update/', FatturaUpdateView.as_view(), name='fattura-update'),
    path('fatture/<int:pk>/delete/', FatturaDeleteView.as_view(), name='fattura-delete'),
    path('fatture/<int:pk>/rigadelete/', RigaFatturaDeleteView.as_view(), name='riga-fattura-delete'),
    path('fatture/<int:pk>/stampa/', FatturaStampaView, name='fattura-stampa'),
    path('fatture/<int:pk>/scarica-xml/', scarica_xml, name='scarica-xml'),
    path('fatture/crea-auto/', CreaFattureAuto.as_view(), name='auto-fatture'),
    path('fatture/conferma-fatture/', ConfermaFattureView.as_view(), name='conferma-fatture'),
    path('schedetv/', SchedaTVListView.as_view(), name='schedetv-list'),
    path('schedetv/<int:pk>/', SchedaTVDetailView.as_view(), name='schedatv-detail'),
    path('schedetv/create/', SchedaTVCreateView.as_view(), name='schedatv-create'),
    path('schedetv/<int:pk>/update/', SchedaTVUpdateView.as_view(), name='schedatv-update'),
    path('schedetv/<int:pk>/delete/', SchedaTVDeleteView.as_view(), name='schedatv-delete'),
    path('schedetv/<int:pk>/rigadelete/', RigaSchedaTVDeleteView.as_view(), name='riga-schedaTV-delete'),
    path('schedetv/crea-schede/', CreaSchedeTV.as_view(), name='crea-schede'),
    path('fatture/scarica-tutte/', scarica_tutte_xml, name='scarica-tutte'),
]