# Generated by Django 5.1.4 on 2025-01-02 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articolo',
            name='prezzo_unitario',
        ),
    ]
