# Generated by Django 5.1.4 on 2025-01-02 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolle', '0002_remove_articolo_prezzo_unitario'),
    ]

    operations = [
        migrations.CreateModel(
            name='RigaBolla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField()),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolle.articolo')),
                ('bolla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe', to='bolle.bolla')),
            ],
        ),
    ]
