# Generated by Django 5.1.4 on 2025-01-02 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolle', '0004_fornitore_tipodocumento_concessionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolla',
            name='concessionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bolle.concessionario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bolla',
            name='tipo_documento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bolle.tipodocumento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='concessionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bolle.concessionario'),
            preserve_default=False,
        ),
    ]
