# Generated by Django 5.1.4 on 2025-01-02 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolle', '0005_bolla_concessionario_bolla_tipo_documento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bolla',
            name='concessionario',
        ),
        migrations.RemoveField(
            model_name='bolla',
            name='tipo_documento',
        ),
        migrations.RemoveField(
            model_name='tipodocumento',
            name='concessionario',
        ),
    ]
