# Generated by Django 5.1.4 on 2025-01-02 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolle', '0007_bolla_concessionario_bolla_tipo_documento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bolla',
            name='concessionario',
        ),
        migrations.AddField(
            model_name='cliente',
            name='concessionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bolle.concessionario'),
            preserve_default=False,
        ),
    ]
