# Generated by Django 5.1.4 on 2025-01-03 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolle', '0008_remove_bolla_concessionario_cliente_concessionario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_documento_predefinito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bolle.tipodocumento'),
        ),
        migrations.AddField(
            model_name='concessionario',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concessionario', to=settings.AUTH_USER_MODEL),
        ),
    ]
