# Generated by Django 5.1.4 on 2025-01-03 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolle', '0009_cliente_tipo_documento_predefinito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articoli', to='bolle.categoria'),
        ),
    ]
