# Generated by Django 5.1.4 on 2025-01-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolle', '0010_alter_articolo_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='rigabolla',
            name='lotto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
