# Generated by Django 5.1.4 on 2025-01-04 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolle', '0011_rigabolla_lotto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('concessionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone', to='bolle.concessionario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zona', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='zona',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clienti', to='bolle.zona'),
        ),
    ]
