# Generated by Django 5.1.4 on 2025-01-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolle', '0012_zona_cliente_zona'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['ordine']},
        ),
        migrations.AddField(
            model_name='categoria',
            name='ordine',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
