# Generated by Django 5.1.4 on 2025-01-05 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolle', '0013_alter_categoria_options_categoria_ordine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(default='0000', max_length=30)),
                ('nome', models.CharField(max_length=255)),
                ('indirizzo', models.TextField()),
                ('piva', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='codice',
            field=models.CharField(default='0000', max_length=30),
        ),
        migrations.AddField(
            model_name='cliente',
            name='proprietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clienti', to='bolle.proprietario'),
        ),
        migrations.CreateModel(
            name='ArticoliConcessi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concessioni', to='bolle.articolo')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articoli_concessi', to='bolle.proprietario')),
            ],
            options={
                'verbose_name': 'Articolo Concesso',
                'verbose_name_plural': 'Articoli Concessi',
                'unique_together': {('proprietario', 'articolo')},
            },
        ),
    ]
