# Generated by Django 5.1.4 on 2025-01-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolle', '0014_proprietario_cliente_codice_cliente_proprietario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietario',
            name='indirizzo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='piva',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
