# Generated by Django 5.1.4 on 2025-01-08 12:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolle', '0015_alter_proprietario_indirizzo_alter_proprietario_piva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolla',
            name='data',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='proprietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clienti', to='bolle.proprietario'),
        ),
    ]
