# Generated by Django 5.1.4 on 2025-01-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolle', '0016_alter_bolla_data_alter_cliente_proprietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cap',
            field=models.CharField(default='00000', max_length=5),
        ),
        migrations.AddField(
            model_name='cliente',
            name='citta',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='cliente',
            name='provincia',
            field=models.CharField(default='SA', max_length=2),
        ),
        migrations.AddField(
            model_name='concessionario',
            name='header',
            field=models.CharField(default='00000000000000000000', max_length=20),
        ),
    ]
