# Generated by Django 5.1.4 on 2025-01-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolle', '0017_cliente_cap_cliente_citta_cliente_provincia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='via',
            field=models.CharField(default='', max_length=255),
        ),
    ]
