# Generated by Django 5.1.4 on 2025-01-12 11:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolle', '0018_cliente_via'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='indirizzo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Carico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.datetime.now)),
                ('numero', models.CharField(default='', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('fornitore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolle.fornitore')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolle.zona')),
            ],
        ),
        migrations.CreateModel(
            name='RigaCarico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lotto', models.CharField(max_length=20)),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolle.articolo')),
                ('carico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe', to='bolle.carico')),
            ],
        ),
    ]
