# Generated by Django 5.1.4 on 2025-01-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolle', '0019_alter_cliente_indirizzo_carico_rigacarico'),
    ]

    operations = [
        migrations.AddField(
            model_name='rigacarico',
            name='quantita',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
