# Generated by Django 5.1.4 on 2025-01-13 16:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolle', '0020_rigacarico_quantita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.datetime.now)),
                ('note', models.TextField(blank=True, null=True)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolle.zona')),
            ],
        ),
        migrations.CreateModel(
            name='RigaReso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField()),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolle.articolo')),
                ('reso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe', to='bolle.reso')),
            ],
        ),
    ]
