# Generated by Django 5.1.4 on 2025-01-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolle', '0021_reso_rigareso'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='prezzo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='articolo',
            name='prezzo_tr',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
