# Generated by Django 5.1.4 on 2025-01-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolle', '0022_articolo_prezzo_articolo_prezzo_tr'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='costo',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='articolo',
            name='iva',
            field=models.PositiveSmallIntegerField(choices=[(4, '4%'), (10, '10%'), (22, '22%')], default=4),
        ),
        migrations.AlterField(
            model_name='articolo',
            name='prezzo',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='articolo',
            name='prezzo_tr',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
