# Generated by Django 5.1.4 on 2025-01-16 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolle', '0023_articolo_costo_articolo_iva_alter_articolo_prezzo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolla',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
