# Generated by Django 5.1.4 on 2025-01-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolle', '0024_alter_bolla_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodocumento',
            name='nome',
            field=models.CharField(max_length=5),
        ),
    ]
