# Generated by Django 5.1.4 on 2025-01-24 16:02

import bolle.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolle', '0025_alter_tipodocumento_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cod_dest',
            field=models.CharField(default='0000000', max_length=7),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pec',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='concessionario',
            name='cap',
            field=models.CharField(default='00000', max_length=5),
        ),
        migrations.AddField(
            model_name='concessionario',
            name='citta',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='concessionario',
            name='cod_dest',
            field=models.CharField(default='0000000', max_length=7),
        ),
        migrations.AddField(
            model_name='concessionario',
            name='iban',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='concessionario',
            name='istituto_finanziario',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='concessionario',
            name='pec',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='concessionario',
            name='provincia',
            field=models.CharField(default='SA', max_length=2),
        ),
        migrations.AddField(
            model_name='concessionario',
            name='via',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='bolla',
            name='data',
            field=models.DateTimeField(blank=True, default=bolle.models.get_aware_datetime, null=True),
        ),
        migrations.CreateModel(
            name='Fattura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.datetime.now)),
                ('numero', models.CharField(default='', max_length=20)),
                ('condizioni_pagamento', models.CharField(choices=[('TP01', 'Pagamento a rate'), ('TP02', 'Pagamento completo'), ('TP03', 'Anticipo')], max_length=4)),
                ('scadenza_pagamento', models.DateField(default=datetime.datetime.now)),
                ('modalita_pagamento', models.CharField(choices=[('MP01', 'Contanti'), ('MP02', 'Assegno'), ('MP03', 'Assegno Circolare'), ('MP05', 'Bonifico'), ('MP08', 'Carta di Pagamento')], max_length=4)),
                ('note', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolle.cliente')),
                ('concessionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolle.concessionario')),
            ],
        ),
        migrations.CreateModel(
            name='RigaFattura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_linea', models.CharField(blank=True, max_length=4, null=True)),
                ('prezzo', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('quantita', models.PositiveIntegerField()),
                ('totale', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('iva', models.PositiveSmallIntegerField(choices=[(4, '4%'), (10, '10%'), (22, '22%')], default=4)),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolle.articolo')),
                ('fattura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe', to='bolle.fattura')),
            ],
        ),
        migrations.CreateModel(
            name='TipoFattura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TD01', 'Fattura'), ('TD04', 'Nota di Credito'), ('TD05', 'Nota di Debito')], max_length=5)),
                ('descrizione', models.CharField(blank=True, max_length=255, null=True)),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
                ('concessionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolle.concessionario')),
            ],
        ),
        migrations.AddField(
            model_name='fattura',
            name='tipo_fattura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolle.tipofattura'),
        ),
    ]
