# Generated by Django 5.1.4 on 2025-01-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolle', '0026_cliente_cod_dest_cliente_pec_concessionario_cap_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rigafattura',
            old_name='totale',
            new_name='imp',
        ),
        migrations.AddField(
            model_name='fattura',
            name='pdf_file',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fattura',
            name='totali',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='fattura',
            name='xml_file',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='rigafattura',
            name='tot_iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
