# Generated by Django 5.1.4 on 2025-01-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolle', '0027_rename_totale_rigafattura_imp_fattura_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fattura',
            name='pdf_file',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='fattura',
            name='xml_file',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
