# Generated by Django 5.1.4 on 2025-01-28 15:43

import bolle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolle', '0028_alter_fattura_pdf_file_alter_fattura_xml_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='concessionario',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='fattura',
            name='totali',
            field=models.JSONField(default=bolle.models.Fattura.default_totali),
        ),
    ]
