# Generated by Django 5.1.4 on 2025-02-28 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolle', '0030_schedatv_rigaschedatv'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrezziPersonalizzati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prezzo', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolle.articolo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolle.cliente')),
            ],
        ),
    ]
