# Generated by Django 5.1.4 on 2025-03-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolle', '0031_prezzipersonalizzati'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codice_fiscale',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='concessionario',
            name='codice_fiscale',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
