# Generated by Django 5.1.4 on 2025-03-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolle', '0032_cliente_codice_fiscale_concessionario_codice_fiscale'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipofattura',
            name='anno',
            field=models.PositiveIntegerField(default=2025),
        ),
    ]
