# Generated by Django 5.1.4 on 2025-03-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolle', '0033_tipofattura_anno'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ignorare',
            field=models.BooleanField(choices=[(4, '4%'), (10, '10%'), (22, '22%')], default=False),
        ),
    ]
