# Generated by Django 5.1.4 on 2025-04-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolle', '0034_cliente_ignorare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ignorare',
            field=models.BooleanField(choices=[(True, 'Ignora'), (False, 'Non Ignorare')], default=False),
        ),
        migrations.AlterField(
            model_name='rigafattura',
            name='imp',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='rigafattura',
            name='tot_iva',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=20),
        ),
    ]
