# Generated by Django 5.1.4 on 2025-04-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolle', '0035_alter_cliente_ignorare_alter_rigafattura_imp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rigafattura',
            name='imp',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='rigafattura',
            name='tot_iva',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=20),
        ),
    ]
