# Generated by Django 5.1.4 on 2025-12-30 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolle', '0036_alter_rigafattura_imp_alter_rigafattura_tot_iva'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.PositiveIntegerField()),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counters', to='bolle.tipodocumento')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tipo', 'anno'), name='uniq_counter_tipo_anno')],
            },
        ),
    ]
