### Get Token
POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
  "username": "oscarvasso",
  "password": "*//warlock94"
}

> {% client.global.set("access_token", response.body.access); %}

### Receipt
GET http://127.0.0.1:8000/api/bolle/1115/receipt/
Authorization: Bearer {{access_token}}

curl.exe -X POST http://127.0.0.1:8000/api/token/ -H "Content-Type: application/json" -d "{\"username\":\"oscarvasso\",\"password\":\"*//warlock94\"}"